### ISSUE TITLE
How to cancel?

### ISSUE THREAD

**Issue by philippeluickx** [imRohan/vue-confirmation-button#1]
This is definitely a very interesting design solution. One thing is missing though: you ask "Are you sure?" and what if I am not? Clicking outside the button should maybe cancel it? Or split the button into 2 options: delete/cancel.

**Comment by imRohan** [comment]
I agree, having some method of canceling the action would be a nice feature to add to the button, especially a split design.

However, I'd like to stay away from hijacking click events outside the button, and leave the reset logic to the end developer (check out the reset() note).

**Comment by philippeluickx** [comment]
Just for reference, this works quite nicely: https://github.com/simplesmiler/vue-clickaway
